export const BASE_API = 'https://imprima.app/api';
// export const BASE_API = 'http://localhost:8000/api';
export const GET_PRODUCTS_BY_KIND = `${BASE_API}/product/?kind_id={kindId}`;
export const GET_PRODUCT = `${BASE_API}/product/{id}`;
export const GET_MERCHANT = `${BASE_API}/merchant/?product_id={id}&cep={cep}`;
export const GET_CATEGORY = `${BASE_API}/category`;
export const GET_CATEGORY_TYPE = `${BASE_API}/product/?category_id={categoryId}&type_id={typeId}`;
export const GET_ATTRIBUTES = `${BASE_API}/merchant_type_attribute/?product_id={productId}&merchant_id={merchantId}`;
export const GET_CHECKOUT_PREFERENCE = `${BASE_API}/checkout/preference`;
export const POST_IMAGE = `${BASE_API}/image`;
