version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    # depends_on:
    #   - migration
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    # command: /env/bin/uvicorn --host 0.0.0.0 --port 80 plata.asgi:app --reload
    # command: >
    #   sh -c "alembic upgrade head && 
    #         uvicorn --host 0.0.0.0 --port 80 plata.asgi:app --reload"

  # migration:
  #   build: .
  #   volumes:
  #     - .:/src
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #   command: /env/bin/alembic upgrade head
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
